/*----------DEFINITION OF A NAMESPACE ACROSS-----------
------------MULTIPLE SOURCE FILES.---------------------
*/
/* THIS PROJECT SHOWS HOW NAMESPACES CAN BE DECLARED,
DEFINED, AND USED. IN THIS PROJECT, THE DECLARATIONS 
OF ELEMENTS OF A NAMESPACE HAVE BEEN DIVIDED BETWEEN
DIFFERENT HEADER FILES. THE DEFINITIONS OF THE 
NAMESPACE ELEMENTS HAS ALSO BEEN DIVIDED BETWEEN DIFFERENT
.cpp FILES. THE SOURCE IN EACH HEADER FILE MUST BE INCLUDED
VIA A #include DIRECTIVE AS NEEDED. HOWEVER, THE .cpp FILES
ARE AUTOMATICALLY COMPILED WITH THE MAIN FILE.
*/

#include "mycommon.h"
#include "nmdecls1.h"
#include "nmdecls2.h"
int main(int argc, char** argv) {
	mynm::funcA();
	mynm::funcB();
	return 0;
}
