#include <iostream>
/*
THIS DEvC++ PROJECT SHOWS THE USE OF USER-DEFINED
FUNCTIONS THAT ARE NOT DEFINED WITHIN THE 
CURRENT SOURCE FILE. THERE ARE TWO WAYS
TO USE SUCH FUNCTIONS.
1. IF THE SOURCE FILE CONTAING THE FUNCTION
DEFINITIONS IS ALREADY A PART OF THE CURRENT 
DevC++ PROJECT, IT WOULD BE NECESSARY TO ADD
TO THE CURRENT SOURCE FILE ONLY THE DECLARATION
OF THOSE FUNCTIONS THAT ARE NEEDED. THE CONTENTS
OF THE OTHER SOURCE FILE CONTAINING THE FUNCTIONS 
WOULD AUTOMATICALLY BE INCLUDED IN THE COMPILATION
OF THE WHOLE PROJECT. FOR THIS PURPOSE, THE 
OTHER FILE MUST FIRST BE ADDED TO THE CURRENT
DevC++ PROJECT IF IT IS NOT ALREADY A PART OF
THE CURRENT PROJECT. THIS MAY BE DONE BY USING
A MENU OPTION IN THE IDE FOR PROJECT.
 
2. IF THE SOURCE FILE CONTAING THE FUNCTION
DEFINITIONS IS NOT A PART OF THE CURRENT DevC++
PROJECT, ITS CONTENTS WOULD NOT AUTOMATICALLY BE
INCLUDED IN THE COMPILATION OF THE WHOLE PROJECT.
ONE APPROCH MAY BE TO PHYSICALLY INSERT WITHIN 
THE CURRENT SOURCE FILE THE CONTENTS (SOURCE CODE)
OF THE OTHER FILE CONTAINING THE FUNCTION DEFINITIONS.
THIS CAN BE DONE BY USING THE #include DIRECTIVE.
FOR EXAMPLE, #include "otherfuncs.cpp". IT WOULD
BE NECESSARY TO ADD TO THE CURRENT SOURCE FILE 
THE DECLARATION THOSE FUNCTIONS THAT ARE NEEDED.
using namespace std;

THE FIRST APPROACH IS USED IN THIS PROJECT.
*/
#include<iostream>
using namespace std;
int showV();
int showD();
int main(int argc, char** argv) {
	showV();
	showD();
	return 0;
}
